### ISSUE TITLE
Suggested fix to bootstrap correctly with surr_req_ci()

### ISSUE THREAD

**Issue by indenkun** [XiaoruiZhu/SurrogateRsq#3]
Thank you for this very interesting package.
I think you are not using bootstrapped data with `surr_req_ci()`. Sorry if I am wrong.

The code for the part bootstrapped by `surr_req_ci()` is as follows:

```r
for (j in 2:B) {
      BS_data <- data[sample(1:n, n, replace = T), ]
      try(
        resultTable[j] <- surr_rsq(reduced_model, full_model,data)[[1]]
      )
      while( is.na(resultTable[j])) {
        BS_data <- data[sample(1:n, n, replace = T), ]
        try(
          resultTable[j] <- surr_rsq(reduced_model, full_model, data)[[1]]
        )
      }

      # ProgressBar
      pb $tick(tokens = list(letter = progress_repNo[j]))
    }
```

The data being bootstrapped and created seems to be `BS_data`, but I don't think this data is given to `surr_req()`.

If you want to use the bootstrapped data, I think you have to do the following:

```r
for (j in 2:B) {
      BS_data <- data[sample(1:n, n, replace = T), ]
      try(
        resultTable[j] <- surr_rsq(reduced_model, full_model, BS_data)[[1]]
      )
      while( is.na(resultTable[j])) {
        BS_data <- data[sample(1:n, n, replace = T), ]
        try(
          resultTable[j] <- surr_rsq(reduced_model, full_model, BS_data)[[1]]
        )
      }

      # ProgressBar
      pb $tick(tokens = list(letter = progress_repNo[j]))
    }
```

However, even if this part is modified as above, the calculation will not be correct, and the next part of `surr_rsq()` needs to be modified:

```r
for (i in 1:avg.num) {
          data$s_full <- surrogate(full_model)
```

I think it would be a good idea to modify this as follows:

```r
full_model[["call"]][["data"]] <- data
full_model <- eval(full_model[["call"]])
        for (i in 1:avg.num) {
          data$s_full <- surrogate(full_model)
```

What I want to do here is to re-evaluate the `full_model` using the data given in the data argument of `surr_rsq()` before passing it to surrogate(), otherwise the surrogate will be using data in the `full_model`, i.e., data that is not passed in the `surr_rsq()` argument.

In essence, it does not use the bootstrapped data, but writes to the bootstrapped data when writing a new column in `data$s_full`.

Sorry I am not explaining it well.

Note that I think this will work for the example listed in the EXAMPLE, but I have not been able to verify it for the other examples.

If this proposal is acceptable, it is reflected in the code that is being forked and can be pulled immediately. Of course, if there is a smarter code, that would be better.

**Comment by XiaoruiZhu** [comment]
Hi, @indenkun Thank you so much for reviewing and using this package. 
Both of your points are right. We missed using the bootstrap data and the full_model also needs to be updated using the bootstrapped data. I appreciate that you provide a solution for them in your forked repo. But I have to use another solution where the full_model's coefficient estimates also need to be updated, following the algorithm proposed in our [paper](https://bpspsychub.onlinelibrary.wiley.com/doi/full/10.1111/bmsp.12289). 

You can see the correct implementation as follows:

```R
BS_data <- data[sample(1:n, n, replace = T), ]
BS_full_model <- update(full_model, data = BS_data)
try(
   resultTable[j] <- surr_rsq(model = reduced_model,
   full_model = BS_full_model)[[1]]
)
```
