### ISSUE TITLE
Making SurrogateRsq work for glm models

### ISSUE THREAD

**Issue by amrosicka** [XiaoruiZhu/SurrogateRsq#6]
Hello, are you planning to make the surr_rsq function work with glm() models?
Glm is explicitly mentioned in the [accompanying paper](https://cran.r-project.org/web/packages/SurrogateRsq/vignettes/JSSpaper.pdf) but when I try to apply the function **surr_rsq()** to my glm model, I get the following error message:
```
Error in UseMethod("getDatafromModel") : 
  no applicable method for 'getDatafromModel' applied to an object of class "c('glm', 'lm')"
```
I really like the concept of surrogate R2 and would love to be able to use it for my analyses. Any update on this would be much appreciated! Thanks!

**Comment by XiaoruiZhu** [comment]
@may-the-bee It is great to hear the Surrogate R2 would be useful for your analyses. Sure, I'll double-check this issue and fix it soon. Thanks for your feedback.

**Comment by XiaoruiZhu** [comment]
@may-the-bee I just want to let you know the issue has been fixed. For the binary response, the logit/probit models can be the models for the goodness of fit analysis using a surrogate R-squared measure. If you're using any other specific models for categorical data analysis and would like to adopt the Surrogate R-squared, please also let me know, I could develop corresponding features for this package.  Thanks for your feedback.

**Comment by amrosicka** [comment]
Thanks @XiaoruiZhu for the fix!
